name: Terraform validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.sha }}
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.14.8
      - name: Terraform Fmt
        run: terraform fmt -check -diff -recursive -no-color
      - name: Terraform Init
        run: terraform init -backend=false -input=false
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          cache: true
      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: TFLint
        run: tflint --format compact --minimum-failure-severity=error
      - name: Terraform docs
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          fail-on-diff: true
