name: Terraform

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-24.04
    steps:
      - uses: cisco-actions-ghe/checkout@f9ed9285a43c795f3f46f9b5f70c82935abf3c6d # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref || github.sha }}
          fetch-depth: 0
      - name: Configure git for private modules
        env:
          GH_READ_TOKEN: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
        run: |
          git config --global url."https://x-access-token:${GH_READ_TOKEN}@github.com/isovalent".insteadOf "ssh://git@github.com/isovalent"
      - uses: cisco-actions-ghe/hashicorp-setup-terraform@74653521a633b678d35d8d82a296404cb93f8a6e # v3.1.2
        with:
          terraform_version: 1.14.8
      - name: Terraform Fmt
        run: terraform fmt -check
        continue-on-error: false
      - name: Terraform Init
        run: terraform init
        continue-on-error: false
      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false
