name: Terraform docs and formatting
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@c2652f7563ff96cd4a5d9e636fff68fc21e40865
  docs:
    needs: formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@d1c99433f7a1e5003ef213d70f89aaa47cb0b675
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          output-format: markdown table
          git-push: "true"